// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // ใช้เครื่องหมาย ['ชื่อตัวแปร'] แทนการใช้จุด เพื่อเลี่ยงปัญหา Type ของ process
    url: process.env["DATABASE_URL"],
  },
});