### Lab 1 - ดึงสินค้าทั้งหมด
GET http://localhost:3000/inventory

### Lab 1 - ดึงสินค้าใกล้หมด
GET http://localhost:3000/inventory?low_stock=true

### Lab 2 - เพิ่มสินค้า
POST http://localhost:3000/inventory
Content-Type: application/json

{
  "name": "BB-001",
  "sku": "CC-002",
  "zone": "A1",
  "quantity": 50,
  "price": 50
}

### Lab 3 - เบิกของออก
PATCH http://localhost:3000/inventory/8967a3bb-e9c3-4ce5-b0b5-b45c4d9c5771/adjust
Content-Type: application/json

{
  "change": -5
}

### Lab 4 - ลบสินค้า (ต้องให้ quantity = 0 ก่อน)
DELETE http://localhost:3000/inventory/8967a3bb-e9c3-4ce5-b0b5-b45c4d9c5771